// A simple <img> wrapper for the nilearn-rendered glass-brain figures.
// Generated by scripts/make_figures.py — these are the canonical visuals.

export default function GlassBrain({ src, alt, caption, className = "" }) {
  return (
    <figure className={`bg-paper2 border border-ink/10 rounded-md overflow-hidden ${className}`}>
      <img
        src={src}
        alt={alt}
        className="w-full h-auto block"
        loading="lazy"
      />
      {caption && (
        <figcaption className="px-4 py-3 text-xs font-mono text-ink2 border-t border-ink/10">
          {caption}
        </figcaption>
      )}
    </figure>
  );
}
